const DRIVERS_TABLE_FIELDS = [
  { dataName: "Driver ID", dataKey: "driver_id", sort: true },
  { dataName: "Email", dataKey: "email", sort: true },
  { dataName: "Status", dataKey: "status", sort: true },
  { dataName: "Status Note", dataKey: "status_note", sort: true },
  { dataName: "First Name", dataKey: "first_name", sort: true },
  { dataName: "Last Name", dataKey: "last_name", sort: true },
  { dataName: "Phone Number", dataKey: "phone_number", sort: true },
  { dataName: "Date of Birth", dataKey: "date_of_birth", sort: true },
  { dataName: "Hiring Date", dataKey: "hiring_date", sort: true },
  { dataName: "Date of Leaving", dataKey: "date_of_leaving", sort: true },
  { dataName: "Reason for Leaving", dataKey: "reason_for_leaving", sort: true },
  {
    dataName: "Driver's License Number",
    dataKey: "drivers_license_number",
    sort: true,
  },
  { dataName: "License Scan", dataKey: "license_scan", sort: false },
  { dataName: "DL Province", dataKey: "dl_province", sort: true },
  { dataName: "DL expiration Date", dataKey: "dl_expiration_date", sort: true },
  {
    dataName: "Abstract Issue Date",
    dataKey: "abstract_issue_date",
    sort: true,
  },
  { dataName: "Abstract Scan", dataKey: "abstract_scan", sort: false },
  {
    dataName: "Criminal Record Check Scan",
    dataKey: "criminal_record_check_scan",
    sort: false,
  },
  {
    dataName: "Criminal Record Check Expiration Date",
    dataKey: "criminal_record_check_expiration_date",
    sort: true,
  },
  { dataName: "TDG Card Date", dataKey: "tdg_card_date", sort: true },
  {
    dataName: "Good to Go Card Date",
    dataKey: "good_to_go_card_date",
    sort: true,
  },
  {
    dataName: "Pre-employment Road Test Date",
    dataKey: "pre_employment_road_test_date",
    sort: true,
  },
  { dataName: "Application Date", dataKey: "application_date", sort: true },
  {
    dataName: "Reference Check Application",
    dataKey: "reference_check_application",
    sort: false,
  },
  {
    dataName: "Consent to Personal Investigation",
    dataKey: "consent_to_personal_investigation",
    sort: false,
  },
  {
    dataName: "Log Book Reviewed Date",
    dataKey: "log_book_reviewed_date",
    sort: true,
  },
  {
    dataName: "Certificate of Violations Scan",
    dataKey: "certificate_of_violations_scan",
    sort: false,
  },
  {
    dataName: "Annual Driver Performance Review",
    dataKey: "annual_driver_performance_review",
    sort: false,
  },
  {
    dataName: "Winter Course Completion Date",
    dataKey: "winter_course_completion_date",
    sort: true,
  },
  {
    dataName: "Winter Course Results",
    dataKey: "winter_course_results",
    sort: true,
  },
  { dataName: "Remarks Comments", dataKey: "remarks_comments", sort: false },
  { dataName: "File Box Number", dataKey: "file_box_number", sort: true },
  { dataName: "Routes", dataKey: "routes", sort: false },
];
export default DRIVERS_TABLE_FIELDS;
